app_name = "localization_management_system"
app_title = "Localization Management System"
app_publisher = "Frappe Technologies"
app_description = "Portal for enhancing communication between Localization Builder and Frappe team"
app_email = "developers@frappe.io"
app_license = "mit"
